### ISSUE TITLE
Menu icon for mobile

### ISSUE THREAD

**Issue by borkdude** [babashka/book#12]
This page has a little Menu icon when you scroll down on mobile: https://tscanlin.github.io/tocbot

We can adopt this too for http://book.babashka.org.

The menu icon appears when the screen is below a certain width, e.g. on mobile and shows the menu when you click on it. 

Tocbot is already used on the page.

**Comment by bolivier** [comment]
It looks like the Tocbot menu is built from scratch using some fancy CSS selectors and hidden checkboxes.  As long as there's some flexibility in the output of asciidoctor, it isn't hard to write (or copy) the required css.

**Comment by borkdude** [comment]
Thanks @dgb23 !
