### ISSUE TITLE
Indentation issue in Explicit Requires section

### ISSUE THREAD

**Issue by frenchy64** [babashka/book#15]
[Here](https://book.babashka.org/#_explicit_requires) the Clojure indentation is off.

<img width="719" alt="Screenshot 2020-12-04 at 3 41 41 PM" src="https://user-images.githubusercontent.com/287396/101212730-38e45c80-3647-11eb-9e1d-606dafdf6d6f.png">

**Comment by borkdude** [comment]
@frenchy64 Thanks a lot. Fixed (may take a few minutes before Github refreshes the content).
