### ISSUE TITLE
Typo in "Input and output flags" section

### ISSUE THREAD

**Issue by dgr** [babashka/book#21]
The "hello bye" examples in the table in the [Input and output flags](https://book.babashka.org/#_input_and_output_flags) section have typos. Currently, the table says:

Input | Input flags | Output flag | *input* | Output
-- | -- | -- | -- | --
{:a 1} {:a 2} |   |   | {:a 1} | {:a 1}
hello bye | -i |   | ("hello" "bye") | ("hello" "bye")
hello bye | -i | -o | ("hello" "bye") | hello bye
{:a 1} {:a 2} | -I |   | ({:a 1} {:a 2}) | ({:a 1} {:a 2})
{:a 1} {:a 2} | -I | -O | ({:a 1} {:a 2}) | {:a 1} {:a 2}

I think this should be:

Input | Input flags | Output flag | *input* | Output
-- | -- | -- | -- | --
{:a 1} {:a 2} |   |   | {:a 1} | {:a 1}
hello bye | -i |   | ("hello bye") | ("hello bye")
hello bye | -i | -o | ("hello bye") | hello bye
{:a 1} {:a 2} | -I |   | ({:a 1} {:a 2}) | ({:a 1} {:a 2})
{:a 1} {:a 2} | -I | -O | ({:a 1} {:a 2}) | {:a 1} {:a 2}

Note the slight difference: "hello" "bye" vs. "hello bye".

**Comment by borkdude** [comment]
Fixed, thanks. Asciidoc has trouble displaying newlines in table cells, which was the issue.
