### ISSUE TITLE
Chapter 6 -x examples need --prn

### ISSUE THREAD

**Issue by jdjohnston** [babashka/book#60]
Or, are `-x` expressions supposed to still be automatically printed?

With newer `babashka`, something like `bb -x clojure.core/identity --hello there` doesn't give an error, but neither is there output.
Adding the `prn` option, `bb --prn -x clojure.core/identity --hello there` works as expected.

**Comment by borkdude** [comment]
We should probably change the examples to:

```
bb -x clojure.core/prn --hello there
```

PR welcome!

**Comment by jdjohnston** [comment]
Interesting idea, but that wouldn't work for the tasks.clj example also in that section

**Comment by borkdude** [comment]
The task could also just use `(prn m)` in the body

**Comment by borkdude** [comment]
@jdjohnston Done! Thank you for bringing this to my attention.

**Comment by borkdude** [comment]
Should be fixed now
