### ISSUE TITLE
'help' override built-in warning

### ISSUE THREAD

**Issue by pwhittin** [babashka/book#65]
Perhaps, in the `Tasks API` section, add an example of using `:override-builtin true`.  For example:
```clojure
help
{:doc "Show help"
:task (my-project.tasks/help-task)
:override-builtin true}
```
Having this documented would have saved me the time it took to unsuccessfully sniff around in the `babashka` source code, and try different things until I figured it out.

**Comment by borkdude** [comment]
Sounds good, do you want to submit a PR?

**Comment by borkdude** [comment]
Done!

**Comment by pwhittin** [comment]
Wow! Such a fast turnaround!  Next time I'll do a PR.
