### ISSUE TITLE
Difference in output between book and current version of bb

### ISSUE THREAD

**Issue by chy-causer** [babashka/book#72]
https://github.com/babashka/book/blob/eea70f8cf5185eb65e87066ddaf36c66fe22bceb/src/cli.adoc?plain=1#L40-L45

The tasks/my-function is a side-effect only (prn m) which returns `nil`, thus for the following:

https://github.com/babashka/book/blob/eea70f8cf5185eb65e87066ddaf36c66fe22bceb/src/cli.adoc?plain=1#L68-L69

I would expect this to give `:x nil` and this is what I found in testing on my v1.3.186 version of bb

```sh
$ bb doit --cli-option :yeah -n 123                                                                            
 {:ns-data 1, :fn-data 1, :task-data 1234, :cli-option :yeah, :num [123]}                                                           
 :x nil                     
```

This differs from the book

https://github.com/babashka/book/blob/eea70f8cf5185eb65e87066ddaf36c66fe22bceb/src/cli.adoc?plain=1#L78-L79

I think I have a commit which fixes this, but feel free to rewrite it yourself as I haven't run through any linters or similar

https://github.com/chy-causer/book/commit/f4e34997bdcd5d39f9151bbcbc75017e3273857a

**Comment by borkdude** [comment]
Good catch. PR welcome.

**Comment by chy-causer** [comment]
Thanks. It's on its way.

**Comment by borkdude** [comment]
Thanks!
